classDiagram
    %% Representação do iPhone e seus papéis (interfaces)
    class iPhone {
        +model : String
        +serialNumber : String
        +osVersion : String
        +makeCallF(number: String)
        +playMusic(track: String)
        +browseWeb(url: String)
    }

    class MusicalPlayer {
        <<interface>>
        +playMusic(track: String)
        +pauseMusic()
        +stopMusic()
    }

    class PhoneDevice {
        <<interface>>
        +makeCall(number: String)
        +receiveCall()
        +endCall()
    }

    class InternetBrowser {
        <<interface>>
        +browseWeb(url: String)
        +openNewTab()
        +closeTab()
    }

    %% Heranças e implementações das interfaces pelo iPhone
    iPhone ..|> MusicalPlayer
    iPhone ..|> PhoneDevice
    iPhone ..|> InternetBrowser
